luci-app-ssr-plus: add VLESS support
fw876/helloworld pull request #170
Opened 2020-08-27 10:00 UTC by xsm1997

Add VLESS support to luci-app-ssr-plus, the next generation protocol of v2ray.

2020-08-28 02:01 UTC, Mattraks commented on luci-app-ssr-plus/root/etc/init.d/shadowsocksr
>  	v2ray) ret="/usr/bin/v2ray/v2ray" && [ ! -f "$ret" ] && ret="/usr/bin/v2ray" ;;
`	vless|v2ray) ret="/usr/bin/v2ray/v2ray" && [ ! -f "$ret" ] && ret="/usr/bin/v2ray" ;;`

2020-08-28 02:03 UTC, Mattraks commented on luci-app-ssr-plus/root/etc/init.d/shadowsocksr
> +	vless) ret="/usr/bin/v2ray/v2ray" && [ ! -f "$ret" ] && ret="/usr/bin/v2ray" ;;
`	vless | v2ray) ret="/usr/bin/v2ray/v2ray" && [ ! -f "$ret" ] && ret="/usr/bin/v2ray" ;;`

2020-08-28 02:11 UTC, Mattraks commented on luci-app-ssr-plus/root/etc/init.d/shadowsocksr
> +	vless) ret="/usr/bin/v2ray/v2ray" && [ ! -f "$ret" ] && ret="/usr/bin/v2ray" ;;
很多地方都可以复用,目前还是有很多地方可以精简优化

2020-08-28 09:37 UTC, xsm1997 commented on luci-app-ssr-plus/root/etc/init.d/shadowsocksr
> +	vless) ret="/usr/bin/v2ray/v2ray" && [ ! -f "$ret" ] && ret="/usr/bin/v2ray" ;;
这里复用合理，但是因为VMess和VLESS是不同的两个协议，未来的差异可能会很大，所以我认为其他地方继续复用不是一个很好的选择。

2020-08-28 09:46 UTC, Mattraks commented on luci-app-ssr-plus/root/etc/init.d/shadowsocksr
> +	vless) ret="/usr/bin/v2ray/v2ray" && [ ! -f "$ret" ] && ret="/usr/bin/v2ray" ;;
我认为你可以能理解错了,参考下ss,ssr毕竟都是一个程序不同类型而已

2020-08-28 09:50 UTC, Mattraks commented on luci-app-ssr-plus/root/etc/init.d/shadowsocksr
> +	vless)
```
	v2ray | vless)
		lua /usr/share/shadowsocksr/genvlessconfig.lua $GLOBAL_SERVER tcp $(uci_get_by_name $1 local_port) >/var/etc/vless-ssr-retcp.json
		sed -i 's/\\//g' /var/etc/$type-ssr-retcp.json
		;;
```
例如这样善于使用变量,整体统一处理变量标识减少重复代码

2020-08-28 09:54 UTC, Mattraks commented on luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua
> +o = s:option(Value, "vless_id", translate("VLESS Id (UUID)"))
这个UUID也可以复用,改个名字照样复用

2020-08-29 00:56 UTC, Mattraks commented on luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua
> +o = s:option(Value, "vless_encryption", translate("VLESS Encryption"))
这个地方有什么用?如果只有"none"建议直接赋值或者使用v2加密列表

2020-08-29 01:12 UTC, xsm1997 commented on luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua
> +o = s:option(Value, "vless_encryption", translate("VLESS Encryption"))
这里是官方VLESS协议适配指南的建议，要做成文本，默认none。

2020-08-31 04:10 UTC, 1715173329 requested changes

2020-08-31 04:10 UTC, 1715173329 commented on luci-app-ssr-plus/root/etc/init.d/shadowsocksr
> +		if [ "$type" == "vless" ]; then
使用“if ... else ... fi”或者“a && b”

2020-08-31 04:10 UTC, 1715173329 commented on luci-app-ssr-plus/root/etc/init.d/shadowsocksr
> +				gen_config="/usr/share/shadowsocksr/genvlessconfig.lua"
同上

2020-08-31 04:10 UTC, 1715173329 commented on luci-app-ssr-plus/root/etc/init.d/shadowsocksr
> +		if [ "$type" == "vless" ]; then
同上

2020-08-31 16:15 UTC, xsm1997 commented
最新提交有typo，待修改，请勿使用

2020-09-01 12:37 UTC, Mattraks commented
建议复位后强制提交以免过多Commits导致后续无法合并
**genv2config.lua -> genv2rayconfig.lua**

```
diff --git a/luci-app-ssr-plus/root/etc/init.d/shadowsocksr b/luci-app-ssr-plus/root/etc/init.d/shadowsocksr
index 658a493..95dbe43 100755
--- a/luci-app-ssr-plus/root/etc/init.d/shadowsocksr
+++ b/luci-app-ssr-plus/root/etc/init.d/shadowsocksr
@@ -115,5 +115,5 @@ find_bin() {
 	ssr-local) ret="/usr/bin/ssr-local" ;;
 	ssr-server) ret="/usr/bin/ssr-server" ;;
-	v2ray) ret="/usr/bin/v2ray/v2ray" && [ ! -f "$ret" ] && ret="/usr/bin/v2ray" ;;
+	v2ray | vless) ret="/usr/bin/v2ray/v2ray" && [ ! -f "$ret" ] && ret="/usr/bin/v2ray" ;;
 	trojan) ret="/usr/sbin/trojan" ;;
 	socks5 | tun) ret="/usr/sbin/redsocks2" ;;
@@ -186,7 +186,7 @@ gen_config_file() {
 		EOF
 		;;
-	v2ray)
-		lua /usr/share/shadowsocksr/genv2config.lua $GLOBAL_SERVER tcp $(uci_get_by_name $1 local_port) >/var/etc/v2-ssr-retcp.json
-		sed -i 's/\\//g' /var/etc/v2-ssr-retcp.json
+	v2ray | vless)
+		lua /usr/share/shadowsocksr/gen${type}config.lua $GLOBAL_SERVER tcp $(uci_get_by_name $1 local_port) >/var/etc/$type-ssr-retcp.json
+		sed -i 's/\\//g' /var/etc/$type-ssr-retcp.json
 		;;
 	trojan)
@@ -344,6 +344,6 @@ start_redir_tcp() {
 		echo "$(date "+%Y-%m-%d %H:%M:%S") Main node:$name $threads Threads Started!" >>/tmp/ssrplus.log
 		;;
-	v2ray)
-		$bin -config /var/etc/v2-ssr-retcp.json >/dev/null 2>&1 &
+	v2ray | vless)
+		$bin -config /var/etc/$type-ssr-retcp.json >/dev/null 2>&1 &
 		echo "$(date "+%Y-%m-%d %H:%M:%S") Main node:$($bin -version | head -1) Started!" >>/tmp/ssrplus.log
 		;;
@@ -393,6 +393,6 @@ start_redir_udp() {
 			echo "$(date "+%Y-%m-%d %H:%M:%S") UDP TPROXY Relay:$name Started!" >>/tmp/ssrplus.log
 			;;
-		v2ray)
-			lua /usr/share/shadowsocksr/genv2config.lua $UDP_RELAY_SERVER udp $(uci_get_by_name $UDP_RELAY_SERVER local_port) >/var/etc/v2-ssr-reudp.json
+		v2ray | vless)
+			lua /usr/share/shadowsocksr/gen${type}config.lua $UDP_RELAY_SERVER udp $(uci_get_by_name $UDP_RELAY_SERVER local_port) >/var/etc/v2-ssr-reudp.json
 			sed -i 's/\\//g' /var/etc/v2-ssr-reudp.json
 			$bin -config /var/etc/v2-ssr-reudp.json >/dev/null 2>&1 &
@@ -440,6 +440,6 @@ start_shunt() {
 			echo "$(date "+%Y-%m-%d %H:%M:%S") Netflix shunt:$name Started!" >>/tmp/ssrplus.log
 			;;
-		v2ray)
-			lua /usr/share/shadowsocksr/genv2config.lua $NETFLIX_SERVER tcp 4321 1088 >/var/etc/v2-ssr-netflix.json
+		v2ray | vless)
+			lua /usr/share/shadowsocksr/gen${type}config.lua $NETFLIX_SERVER tcp 4321 1088 >/var/etc/v2-ssr-netflix.json
 			$bin -config /var/etc/v2-ssr-netflix.json >/dev/null 2>&1 &
 			dns2socks 127.0.0.1:1088 8.8.8.8:53 127.0.0.1:5555 -q >/dev/null 2>&1 &
@@ -494,6 +494,6 @@ start_local() {
 		echo "$(date "+%Y-%m-%d %H:%M:%S") Global_Socks5:$name Started!" >>/tmp/ssrplus.log
 		;;
-	v2ray)
-		lua /usr/share/shadowsocksr/genv2config.lua $local_server tcp 0 $(uci_get_by_type socks5_proxy local_port 1080) >/var/etc/v2-ssr-local.json
+	v2ray | vless)
+		lua /usr/share/shadowsocksr/gen${type}config.lua $local_server tcp 0 $(uci_get_by_type socks5_proxy local_port 1080) >/var/etc/v2-ssr-local.json
 		sed -i 's/\\//g' /var/etc/v2-ssr-local.json
 		$bin -config /var/etc/v2-ssr-local.json >/dev/null 2>&1 &

```

2020-09-01 14:34 UTC, xsm1997 commented
已修正问题，并强制提交。

2020-09-02 02:45 UTC, merged