readme 中增加添加 ucl upx 的说明。
fw876/helloworld pull request #711
Opened 2021-11-13 05:39 UTC by VergilGao

参考 https://github.com/coolsnowwolf/lede/issues/3642#issuecomment-596123091

2021-11-14 13:04 UTC, 1715173329 requested changes

2021-11-14 13:04 UTC, 1715173329 commented on README.md
> +tools-y += ucl upx' tools/Makefile
这里不应有 `' tools/Makefile` 。

2021-11-14 13:04 UTC, 1715173329 commented on README.md
> +You should manually add the following code after tools/Makefile:
我建议把这段描述添加到 svn checkout 下面。
```suggestion
Then add them to `tools/Makefile`:
```

2021-11-15 01:00 UTC, VergilGao commented on README.md
> +sed -i 'N;24a\tools-y += ucl upx' tools/Makefile
因为那个Makefile的结尾部分是一个编译指令，所以不能直接追加在行位，我挑的这两个行数是混在了他原来文件对应的指令的区域里，如果他没有大的变化是没啥问题的。
主要我也没想出来有什么更好的方案。

2021-11-15 01:33 UTC, VergilGao commented
review过了之后如果觉得commit太多我可以 -f 一下

2021-11-15 05:07 UTC, 1715173329 commented on README.md
> +sed -i 'N;24a\tools-y += ucl upx' tools/Makefile
或许我们可以用这个软件包
https://github.com/kuoruan/openwrt-upx

2021-11-15 09:11 UTC, 1715173329 approved these changes
虽然我个人还有一些细节上的看法，不过之后再说 ;)
LGTM - Thanks!

2021-11-15 09:13 UTC, merged

2021-11-16 01:12 UTC, VergilGao commented
> 虽然我个人还有一些细节上的看法，不过之后再说 ;) LGTM - Thanks!

其实我也不是很喜欢硬编码行号的方案，但是我对openwrt的sdk结构不是很熟悉，都是临时看他源码猜测的，所以也实在不太清楚还有哪些替代的方案。

2021-11-16 05:01 UTC, 1715173329 commented
我是指排版方面啦～